spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/library
    username: postgres # default
    password: password # default
  jpa:
    show-sql: false
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        ddl-auto: none
  sql:
    init:
      mode: always
      data-locations: "classpath:data.sql"
      schema-locations: "classpath:schema.sql"

