DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS
(
    id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    full_name VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES
(
    id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS
(
    id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    author BIGINT NOT NULL,
    genre BIGINT NOT NULL,
    FOREIGN KEY (author) REFERENCES AUTHORS (id),
    FOREIGN KEY (genre) REFERENCES GENRES (id)
);
